fields:
- name: id
  type: string
  required: true
  unique: true
- name: titulo
  type: string
  required: true
  unique: false
- name: fecha
  type: date
  format: YYYY-MM-DD
  required: false
  unique: false
- name: url
  type: string
  required: true
  unique: true
  format: https?://.*
- name: fuente
  type: string
  required: true
  unique: false
- name: autor
  type: string
  required: false
  unique: false
- name: capturado_ts
  type: datetime
  format: ISO8601
  required: true
  unique: false
